/**
 * capacitor-pipe — YouTube extraction for Capacitor.
 *
 * Extraction is attempted with PipePipeExtractor first and falls back to
 * NewPipeExtractor. The two are independent engines: PipePipe defers signature
 * and `n`-parameter deciphering to a PipePipe-hosted service, while NewPipe runs
 * it locally in Rhino. They therefore fail for different reasons, which is what
 * makes the fallback worth having.
 */

/** Which extractor produced a result. */
export type ExtractionEngine = 'pipepipe' | 'newpipe';

/** One engine's attempt at an extraction, successful or not. */
export interface EngineAttempt {
  engine: ExtractionEngine;
  ok: boolean;
  /** Failure reason. Absent when `ok` is true. */
  error?: string;
  /** Exception class name, useful for distinguishing age-gating from geo-blocking. */
  errorType?: string;
  durationMs: number;
}

/**
 * How a stream's bytes are obtained.
 *
 * `SABR` streams have no fetchable URL — they are a session you must drive.
 * Use {@link PipePlugin.openSabrSession} for those.
 */
export type DeliveryMethod = 'PROGRESSIVE_HTTP' | 'DASH' | 'HLS' | 'SS' | 'SABR' | 'TORRENT';

export type StreamType =
  | 'VIDEO_STREAM'
  | 'AUDIO_STREAM'
  | 'LIVE_STREAM'
  | 'AUDIO_LIVE_STREAM'
  | 'POST_LIVE_STREAM'
  | 'POST_LIVE_AUDIO_STREAM'
  | 'NONE';

/** Fields shared by every stream variant. */
export interface BaseStream {
  /**
   * A media URL, or an inline manifest when `isUrl` is false.
   * Empty for `SABR` streams — open a SABR session instead.
   */
  content: string;
  /** False when `content` holds an inline manifest rather than a URL. */
  isUrl: boolean;
  deliveryMethod: DeliveryMethod;
  /** Container/codec name, e.g. `MPEG_4`, `WEBMA_OPUS`. */
  format: string;
  mimeType?: string;
  /** YouTube format id. */
  itag?: number;
  codec?: string;
  contentLength?: number;
  /** Byte range of the initialisation segment, for DASH assembly. */
  initStart?: number;
  initEnd?: number;
  /** Byte range of the segment index, for DASH assembly. */
  indexStart?: number;
  indexEnd?: number;
}

export interface VideoStream extends BaseStream {
  resolution: string;
  width?: number;
  height?: number;
  fps?: number;
  /** True for adaptive video tracks that carry no audio. */
  isVideoOnly: boolean;
}

export interface AudioStream extends BaseStream {
  /** Average bitrate in bits per second. */
  bitrate: number;
  /** Track id for multi-language audio, e.g. `en.4`. */
  audioTrackId?: string;
  audioTrackName?: string;
  /** True for the video's original-language audio. */
  isOriginalAudio?: boolean;
  /** True for dynamic-range-compressed tracks. */
  isDrc?: boolean;
}

export interface SubtitleStream extends BaseStream {
  languageCode: string;
  /** True when the track was machine-generated rather than authored. */
  autoGenerated: boolean;
}

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
  estimatedResolutionLevel: 'HIGH' | 'MEDIUM' | 'LOW' | 'UNKNOWN';
}

export type SponsorBlockCategory =
  | 'SPONSOR'
  | 'INTRO'
  | 'OUTRO'
  | 'INTERACTION'
  | 'HIGHLIGHT'
  | 'SELF_PROMO'
  | 'NON_MUSIC'
  | 'PREVIEW'
  | 'FILLER'
  | 'PENDING';

export interface SponsorBlockSegment {
  uuid: string;
  category: SponsorBlockCategory;
  /** Either a span to skip, or a single point of interest. */
  action: 'SKIP' | 'POI';
  startTimeMs: number;
  endTimeMs: number;
}

export interface StreamInfo {
  id: string;
  url: string;
  title: string;
  /** Duration in seconds. */
  duration: number;
  streamType: StreamType;
  isLive: boolean;

  uploader: string;
  uploaderUrl?: string;
  uploaderAvatarUrl?: string;
  uploaderVerified?: boolean;
  uploaderSubscriberCount?: number;

  viewCount: number;
  likeCount?: number;
  /** Restored via ReturnYouTubeDislike where the engine supports it. */
  dislikeCount?: number;

  description?: string;
  textualUploadDate?: string;
  /** ISO-8601 upload timestamp. */
  uploadDate?: string;
  category?: string;
  tags?: string[];

  /** Highest-resolution thumbnail, kept for convenience. */
  thumbnailUrl: string;
  thumbnails: Thumbnail[];

  videoStreams: VideoStream[];
  audioStreams: AudioStream[];
  videoOnlyStreams: VideoStream[];
  subtitles: SubtitleStream[];

  sponsorBlockSegments?: SponsorBlockSegment[];

  /**
   * True when YouTube served this video only over SABR, meaning the stream
   * arrays contain no directly playable URL. Open a SABR session to play it.
   */
  requiresSabr: boolean;
}

export interface StreamInfoResult {
  success: boolean;
  error?: string;
  /** The engine that produced `streamInfo`. Absent when every engine failed. */
  engine?: ExtractionEngine;
  /** Every engine tried, in order, including the ones that failed. */
  attempts: EngineAttempt[];
  streamInfo?: StreamInfo;
}

export interface ExtractStreamInfoOptions {
  videoUrl: string;
  /**
   * Restrict extraction to these engines, in this order.
   * Defaults to `['pipepipe', 'newpipe']`.
   */
  engines?: ExtractionEngine[];
  /** Fetch SponsorBlock segments. Best-effort; never blocks extraction. Default false. */
  sponsorBlock?: boolean;
  /** BCP-47 localisation, e.g. `en-GB`. Affects what YouTube returns, not just formatting. */
  localization?: string;
  /** ISO-3166 country code. Affects availability and recommendations. */
  contentCountry?: string;
}

/** A format offered by a SABR session. */
export interface SabrFormat {
  itag: number;
  mimeType: string;
  kind: 'audio' | 'video';
  width?: number;
  height?: number;
  bitrate?: number;
  audioTrackId?: string;
  approxDurationMs?: number;
}

export interface OpenSabrSessionOptions {
  videoUrl: string;
  /**
   * Start position in milliseconds. The session preloads around this point,
   * so setting it avoids a wasted seek on resume. Default 0.
   */
  startPositionMs?: number;
  /** Preferred audio track id for multi-language videos. */
  audioTrackId?: string;
}

export interface SabrSessionResult {
  success: boolean;
  error?: string;

  /** Handle for {@link PipePlugin.closeSabrSession} and for native player lookup. */
  sessionId?: string;

  /**
   * A DASH manifest served on loopback, e.g.
   * `http://127.0.0.1:52731/<sessionId>/manifest.mpd`.
   *
   * Playable by any web player (dash.js, Shaka) and by Media3's
   * `DashMediaSource`. This is the portable path — it needs no native wiring.
   */
  manifestUrl?: string;

  /**
   * True when Media3 is on the app's classpath, meaning native code can build a
   * zero-copy MediaSource with
   * `PipeSabr.mediaSourceFactory(sessionId)` instead of going over loopback.
   */
  nativePlaybackAvailable?: boolean;

  formats?: SabrFormat[];
  isLive?: boolean;
  durationMs?: number;
}

export interface PoTokenOptions {
  /** The 11-character YouTube video id the token was minted for. */
  videoId: string;
  /** Visitor identity the token is bound to. */
  visitorData: string;
  /** InnerTube client version the token was minted against. */
  clientVersion: string;
  /** The minted Proof-of-Origin token. */
  playerPoToken: string;
  /**
   * Lifetime in milliseconds. Defaults to just under 12 hours, matching the
   * integrity token a PO token is derived from. Pass 0 for no expiry.
   */
  ttlMs?: number;
}

/** Availability of each engine and of the optional native playback path. */
export interface EngineStatus {
  /** Engines present on the classpath, in fallback order. */
  available: ExtractionEngine[];
  pipePipeVersion?: string;
  newPipeVersion?: string;
  /** True when androidx.media3 was found, enabling the native MediaSource path. */
  media3Available: boolean;
  /** Port the loopback SABR server is bound to, once a session has been opened. */
  loopbackPort?: number;
}

export interface PipePlugin {
  /**
   * Extract stream information for a YouTube URL.
   *
   * Tries PipePipeExtractor first, then falls back to NewPipeExtractor.
   * `attempts` reports what each engine did, so a partial failure is visible
   * even when the call ultimately succeeds.
   */
  extractStreamInfo(options: ExtractStreamInfoOptions): Promise<StreamInfoResult>;

  /**
   * Open a SABR playback session.
   *
   * Required for videos where `streamInfo.requiresSabr` is true — SABR serves no
   * plain URL, so bytes only arrive by driving the protocol. Returns a loopback
   * DASH manifest any player can consume. Always pair with
   * {@link PipePlugin.closeSabrSession}; sessions hold a segment cache and a
   * WebView-minted token.
   *
   * Call {@link PipePlugin.providePoToken} for this video first — without a
   * token this call fails.
   */
  openSabrSession(options: OpenSabrSessionOptions): Promise<SabrSessionResult>;

  /** Tear down a SABR session and release its cache, tokens and loopback routes. */
  closeSabrSession(options: { sessionId: string }): Promise<void>;

  /**
   * Supply a Proof-of-Origin token for a video, before opening its SABR session.
   *
   * YouTube refuses media for gated videos without one, and the extractor never
   * mints tokens — producing one means running Google's BotGuard challenge in a
   * real JavaScript runtime, exchanging the snapshot for an integrity token
   * (~12h), then deriving a per-video token from it. There is no offline path;
   * the signing secret never leaves Google's servers.
   *
   * Tokens are per-video: reusing one across videos fails attestation.
   *
   * **Required, not optional.** The MWEB player request that SABR depends on
   * dereferences the token for its client version, visitor data and poToken, so
   * `openSabrSession` fails outright without one — it does not fall back to an
   * unattested session.
   */
  providePoToken(options: PoTokenOptions): Promise<void>;

  /** Report which engines and playback paths are available at runtime. */
  getEngineStatus(): Promise<EngineStatus>;
}
